spring.data.mongodb.uri: mongodb+srv://samurai:eP8VTkfXFJczOQDT@cluster0.x6j48.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
server:
  servlet:
    context-path: /api/v1
  port: 8080

#spring:
#  data:
#    mongodb:
#      host: mongodb+srv://cluster0.x6j48.mongodb.net
#      database: myFirstDatabase
#      username: samurai
#      password: eP8VTkfXFJczOQDT